// Auto-generated by `supabase gen types typescript`.
// Replaced after Step 14 마이그레이션 적용 + `mcp__supabase__generate_typescript_types`.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = Record<string, unknown>;
